version: "3.5"
services:
  arkserver:
    build:
      dockerfile: ./Dockerfile
    image: arkserver
    user: steam
    volumes:
      - type: bind
        target: /home/steam/ark/ShooterGame/Saved
        source: ./Saved

    ports:
      - "7777:7777/udp"
      - "7778:7778/udp"
      - "27015:27015/udp"
      - "27020:27020/tcp"

    command: bash -c "steamcmd +force_install_dir /home/steam/ark/ +login anonymous +app_update 376030 +quit && /home/steam/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?MaxPlayers=20?Port=7777?QueryPort=27015 -nosteamclient -server -log"
